# Generated by Django 4.2 on 2023-04-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='film',
            field=models.CharField(max_length=300),
        ),
    ]
