# Generated by Django 4.2 on 2023-04-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
