# Generated by Django 4.2 on 2023-04-14 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_owner_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='owner',
        ),
    ]
