# Generated by Django 4.2 on 2023-04-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_forgot_password_reset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='activation_code',
        ),
    ]
