# Generated by Django 4.2 on 2023-04-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_rename_owner_comments_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='owner',
        ),
    ]
